### ISSUE TITLE
Haptic Feedback (vibration) sporadically spams while using app

### ISSUE THREAD

**Issue by theofandrich** [harmony-one/x#345]
When using "Suprise ME!" and "Press & Hold" interchangeably, during the thinking portion of the visual feedback, it occasionally bugs out and vibrates incessantly.

**Comment by Aishlia** [comment]
Theo F and I currently cannot replicate.

**Comment by theofandrich** [comment]
We believe this is a bug only on older versions. If this bug reemerges, we will open back up this issue.
